TELEMETRY_CPU_LOAD_AVG = 'CPU_LOAD_AVG'
TELEMETRY_CPU_TIMES = 'CPU_TIMES'
TELEMETRY_CPU_TIMES_PER_CPU = 'CPU_TIMES_PER_CPU'
TELEMETRY_CPU_PERCENT = 'CPU_PERCENT'
TELEMETRY_CPU_PERCENT_PER_CPU = 'CPU_PERCENT_PER_CPU'
TELEMETRY_CPU_TIMES_PERCENT = 'CPU_TIMES_PERCENT'
TELEMETRY_CPU_TIMES_PERCENT_PER_CPU = 'CPU_TIMES_PERCENT_PER_CPU'

TELEMETRY_MEM_SYSTEM = 'MEM_SYSTEM'
TELEMETRY_MEM_SWAP = 'MEM_SWAP'

TELEMETRY_DISK_USAGE = 'DISK_USAGE'
TELEMETRY_DISK_IO_COUNTERS = 'DISK_IO_COUNTERS'
TELEMETRY_DISK_IO_COUNTERS_PER_DISK = 'DISK_IO_COUNTERS_PER_DISK'

TELEMETRY_NET_IO_COUNTERS = 'NET_IO_COUNTERS'
TELEMETRY_NET_IO_COUNTERS_PER_NIC = 'NET_IO_COUNTERS_PER_NIC'
TELEMETRY_NET_CONNECTIONS = 'NET_CONNECTIONS'


TELEMETRY_PROCESS_CPU_AFFINITY = 'PROC_CPU_AFFINITY'

TELEMETRY_PROCESS_MEM_INFO = 'PROC_MEM_INFO'
TELEMETRY_PROCESS_MEM_PERCENT = 'PROC_MEM_PERCENT'
TELEMETRY_PROCESS_MEM_MAP = 'PROC_MEM_MAP'

TELEMETRY_PROCESS_DISK_OPEN_FILES = 'PROC_OPEN_FILES'

TELEMETRY_PROCESS_NET_CONNECTIONS = 'PROC_NET_CONNECTIONS'
